=== fnhego/hojadevida/public_html/xml/curso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="curso">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="estudiante"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="estudiante">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="codigo" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element ref="notas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="notas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nota" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== fnhego/hojadevida/public_html/xml/curso.xml
<?xml version="1.0" encoding="UTF-8"?>
<curso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="curso.xsd">
  <estudiante>
    <codigo>20171094020</codigo>
    <nombre>Juan Torres</nombre>
    <notas>
      <nota>4.8</nota>
      <nota>3.9</nota>
      <nota>4.5</nota>
    </notas>
  </estudiante>
</curso>
